export {default as Dashboard} from './Home/Dashboard.jsx'
export {default as Login} from './Login/Login.jsx'
export {default as Register} from './Register/Register.jsx'
export {default as ForgotPassword} from './ForgotPassword/ForgotPassword.jsx'
export {default as NotFound} from './Errors/404.jsx'